name: .NET Core CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }} 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        svc:
          - name: IdentityService
            dockerfile: ./IdentityService/Dockerfile
          - name: NotificationService
            dockerfile: ./NotificationService/Dockerfile
          - name: NutritionService
            dockerfile: ./NutritionService/Dockerfile
          - name: ReportsService
            dockerfile: ./ReportsService/Dockerfile
          - name: UserProfileService
            dockerfile: ./UserProfileService/Dockerfile
          - name: UserTrainingTrackingService
            dockerfile: ./UserTrainingTrackingService/Dockerfile
          - name: WorkoutCatalogService
            dockerfile: ./WorkoutCatalogService/Dockerfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker Hub repository name
        id: repo
        run: |
          DOCKER_USERNAME="${{ secrets.DOCKER_USERNAME }}"
          REPO_NAME="fitnessproject"
          echo "repo_name=$DOCKER_USERNAME/$REPO_NAME" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set dynamic image tag
        id: vars
        run: echo "tag=${{ matrix.svc.name }}-${GITHUB_REF_NAME}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build and push service image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.svc.dockerfile }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ steps.repo.outputs.repo_name }}:${{ matrix.svc.name }}-${{ steps.vars.outputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore Fitness-Project.sln

      - name: Build
        run: dotnet build TaskCicd/TaskCicd.csproj --no-restore --configuration Release
